### ISSUE TITLE
Improve locking for vectors/matrices?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-la#18]
Currently, we are locking the whole matrix for both read and write operations. This may limits parallelism too much. 
There are two things we could investigate too improve on the situation:
1. Use ```shared_mutex``` ([C++17](http://en.cppreference.com/w/cpp/thread/shared_mutex) or [Boost](http://www.boost.org/doc/libs/1_63_0/doc/html/thread/synchronization.html#thread.synchronization.mutex_types.shared_mutex)) to allow for parallel reads
2. Do not lock the whole matrix for operations like ```set_entry``` that only affect a single entry. This could be done by using several mutexes (maybe one mutex per row?)

**Comment by ftalbrecht** [comment]
Sounds good to me! The 2nd option could be a good one, where we lock the outer storage for sparse matrices (in the currently implemented cases the rows); should not increase memory footprint too much. I have no idea what a `shared_mutex` does, though... :)

**Comment by renemilk** [comment]
Conceptually shared_mutex would be nice, yes. We cannot use the std one though, since our maximum feature wise is currently gcc 4.9. Boost one would be fine if it's compatible with that, I couldn't tell from the docs though. 

My personal current max for boost is 1.61 btw, the docs also don't say when it was introduced. 

Out of curiosity, did you @tobiasleibner profile spin time/overhead in a real application with vtune for example?

**Comment by tobiasleibner** [comment]
The shared_mutex in Boost requires C++14, if I understand correctly. GCC 4.9 has incomplete support for C++14, so it might or might not work. 
I had problems using one of our sparse matrices when trying to parallelize the implicit timestepping for my finite volume code, where locking and spin time was most of the execution time (profiled with vtune). On second thought, that parallelization approach would not be the best even if there was no locking, but I thought it might also be a problem when doing matrix assemblies from several threads. I have no measurements on that, though.
