### ISSUE TITLE
Eigensolver tests fails on arch

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-la#41]
https://travis-ci.org/dune-community/dune-xt-la/jobs/348219899

**Comment by tobiasleibner** [comment]
Probably a different version of LAPACK is used, thus the computed eigenvalues differ slightly. We could either increase the tolerance or use the same version of LAPACK as in the other tests.

**Comment by renemilk** [comment]
IIRC @ftalbrecht questioned the usefulness of some of the failing tests altogether. So re-writing or removing them may be in order before adjusting any tolerances. I would definitely prefer that to forcing everybody to use the same lapack version/implementation.

**Comment by ftalbrecht** [comment]
Indeed. Since we cannot know or enforce which eigenvectors the solver chooses to spane the eigenspace, the check I added to compare eigenvectors with expected ones does not make sense. We should keep the  checks for the eigenvalues and the eigendecomposition, both for the complex/real case.

I will take a look if I have the time, otherwise feel free to adjust the tests...

**Comment by tobiasleibner** [comment]
I think we can simply remove the ``gives_correct*eigenvectors*`` tests. The eigenvector property of the computed eigenvectors is already tested in the ``gives_correct*eigendecomposition`` methods. 
Then we just need to increase the tolerances for the ``gives_correct*eigenvalue*`` methods.

**Comment by TiKeil** [comment]
In #44 I fixed this issue by removing the eigenvector tests and adjusting the tolerances for lapack. Furthermore I removed the test of eigenvalue_in_correct order since in general there is no correct order.

**Comment by tobiasleibner** [comment]
Fixed by #44.
